server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://gateway:8000/api/;
    }

    location /auth/ {
        proxy_pass http://gateway:8000/auth/;
    }

    location /admin/ {
        proxy_pass http://gateway:8000/admin/;
    }
}
